package com;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("value1")
	private java.math.BigDecimal value1;

	@org.kie.api.definition.type.Label("value2")
	private java.math.BigDecimal value2;

	public Person() {
	}

	public java.math.BigDecimal getValue1() {
		return this.value1;
	}

	public void setValue1(java.math.BigDecimal value1) {
		this.value1 = value1;
	}

	public java.math.BigDecimal getValue2() {
		return this.value2;
	}

	public void setValue2(java.math.BigDecimal value2) {
		this.value2 = value2;
	}

	@Override
	public String toString() {
		return "ResultValue [value1=" + value1 + ", value2=" + value2 + "]";
	}

	public Person(java.math.BigDecimal value1, java.math.BigDecimal value2) {
		this.value1 = value1;
		this.value2 = value2;
	}
}